item {
    id: 1
    name: 'BlueFish1'
}
item {
    id: 2
    name: 'BlueFish2'
}
item {
    id: 3
    name: 'Dolphin1'
}
item {
    id: 4
    name: 'Dolphin2'
}
item {
    id: 5
    name: 'Fisherman'
}
item {
    id: 6
    name: 'DeepSeaFish'
}
item {
    id: 7
    name: 'SeaDiver'
}
